server {
    listen 443 ssl;
    server_name scrumboard.ddev.site;

    location /@vite/ {
        proxy_pass http://localhost:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}